### ISSUE TITLE
i have a error

### ISSUE THREAD

**Issue by zhangting1994** [KaiyangZhou/deep-person-reid#90] opened 2018-12-26 02:35 UTC
File "train_imgreid_xent.py", line 266, in <module>
    main()
  File "train_imgreid_xent.py", line 91, in main
    distmat = test(model, queryloader, galleryloader, use_gpu, return_distmat=True)
  File "train_imgreid_xent.py", line 250, in test
    cmc, mAP = evaluate(distmat, q_pids, g_pids, q_camids, g_camids, use_metric_cuhk03=args.use_metric_cuhk03)
  File "/mnt/hdd/Private/zhangting/deep-person-reid/torchreid/eval_metrics.py", line 161, in evaluate
    return evaluate_cy(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03)
  File "eval_metrics_cy.pyx", line 21, in eval_metrics_cy.evaluate_cy
  File "eval_metrics_cy.pyx", line 29, in eval_metrics_cy.evaluate_cy
  File "eval_metrics_cy.pyx", line 226, in eval_metrics_cy.eval_market1501_cy
AssertionError: Error: all query identities do not appear in gallery

**Comment by KaiyangZhou** [comment] 2018-12-26 10:39
what command did you use?

**Comment by zhangting1994** [comment] 2019-01-02 02:35
I use the flowing command
python train_imgreid_xent.py \
-s market1501 \
-t market1501 \
--height 256 \
--width 128 \
--test-batch-size 100 \
--evaluate \
--visualize-ranks \
-a se_resnet50_fc512 \
--load-weights log/se_resnet50_fc512-market-xent/checkpoint_ep60.pth.tar \
--save-dir log/eval-resnet50 \
--gpu-devices 0 \

**Comment by KaiyangZhou** [comment] 2019-01-02 08:53
that's weird, I could not reproduce your error. Are you using the latest commit?

It would be better if you could provide more details about the error log.

**Comment by KaiyangZhou** [comment] 2019-02-04 23:17
I am considering closing this if no further error is reported.

Feel free to report if anything is wrong.

**Closed by KaiyangZhou** 2019-02-04 23:17 UTC

**Comment by kthumar1997** [comment] 2019-06-08 07:41
Hello @KaiyangZhou i'm facing same error. I made my own dataset for testing purpose.(ref - [here](https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#use-your-own-dataset))

The following is the directory structure of the dataset.

> /media/User/XXX/Re_Id/Testdata/gallery (contains in\mages in random)
>     /media/User/XXX/Re_Id/Testdata/gallery/cam01
>            /media/User/XXX/Re_Id/Testdata/gallery/cam01/person01_cam01_frame026.jpg
>            /media/User/XXX/Re_Id/Testdata/gallery/cam01/person06_cam03_frame136.jpg
>            /media/User/XXX/Re_Id/Testdata/gallery/cam01 /person03_cam02_frame054.jpg
>            (and so in in each folder)
>     /media/User/XXX/Re_Id/Testdata/gallery/cam02
>     /media/User/XXX/Re_Id/Testdata/gallery/cam03
>
> /media/User/XXX/Re_Id/Testdata/queue (contains only one image)
>     /media/User/XXX/Re_Id/Testdata/queue/cam01_person01_frame635.jpg 
>
> /media/User/XXX/Re_Id/Testdata/train
>     /media/User/XXX/Re_Id/Testdata/tarin/cam01 (images of person(1 - 9) in their respective folder)
>             /media/User/XXX/Re_Id/Testdata/tarin/cam01/person01/
>                     /media/User/XXX/Re_Id/Testdata/tarin/cam01/person01/cam01_person01_frame001.jpg
>                     /media/User/XXX/Re_Id/Testdata/tarin/cam01/person01/cam01_person01_frame002.jpg
>                     (and so on in each one. ...)
>     /media/User/XXX/Re_Id/Testdata/train/cam02 (images of person(1 - 9) in their respective folder)
>     /media/User/XXX/Re_Id/Testdata/train/cam03 (images of person(1 - 9) in their respective folder)

I've converted the dataset in the format mentioned [here.](https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#use-your-own-dataset)

My NewDatset.py contains the following code.

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os
import os.path as osp
import torchreid
from torchreid.data import ImageDataset


class NewDataset(ImageDataset):
    dataset_dir = 'new_dataset'

    def __init__(self, root='', **kwargs):
        self.root = osp.abspath(osp.expanduser(root))
        self.dataset_dir = osp.join(self.root, self.dataset_dir)
        print("[INFO] dataset_dir: ",self.dataset_dir)

        imgPath = "/media/User/XXX/Re_Id/Testdata/train/"
        queryPath = "/media/User/XXX/Re_Id/Testdata/queue/"
        galleryPath =" /media/User/XXX/Re_Id/Testdata/gallery /"

        dataList = []
        queryList = []
        galleryList = []

        for subdir, dirs, files in os.walk(imgPath):
            for file in files:
                dataList.append(os.path.join(subdir, file))
                split = file.split('_')
                pid = int((split[0])[-2:])
                dataList.append(pid)
                camid = int((split[1])[-2:])
                dataList.append(camid)
        dataZip = [i for i in zip(*[iter(dataList)] * 3)]
        print("[INFO] DataList lenght ", len(dataList))

        for subdir, dirs, files in os.walk(galleryPath):
            for file in files:
                galleryList.append(os.path.join(subdir, file))
                split = file.split('_')
                pid = int((split[0])[-2:])
                galleryList.append(pid)
                camid = int((split[1])[-2:])
                galleryList.append(camid)
        galleryZip = [i for i in zip(*[iter(galleryList)] * 3)]
        print("[INFO] Gallery length ",len(galleryList))



        for subdir, dirs, files in os.walk(queryPath):
            for file in files:
                queryList.append(os.path.join(subdir, file))
                split = file.split('_')
                pid = int((split[0])[-2:])
                queryList.append(pid)
                camid = int((split[1])[-2:])
                queryList.append(camid)
        queryZip = [i for i in zip(*[iter(queryList)] * 3)]
        print("[INFO] Query Length :", len(queryList))

        train = dataZip

        query = queryZip

        gallery = galleryZip
        # Each list contains tuples of (img_path, pid, camid)

        super(NewDataset, self).__init__(train, query, gallery, **kwargs)

torchreid.data.register_image_dataset('new_dataset', NewDataset)

# use your own dataset only
datamanager = torchreid.data.ImageDataManager(
    root='reid-data',
    sources='new_dataset'
)


model = torchreid.models.build_model(
    name='mlfn',
    num_classes=datamanager.num_train_pids,
    loss='softmax',
    pretrained=True
)

model = model.cuda()

optimizer = torchreid.optim.build_optimizer(
    model,
    optim='adam',
    lr=0.0003
)


scheduler = torchreid.optim.build_lr_scheduler(
    optimizer,
    lr_scheduler='single_step',
    stepsize=20
)

engine = torchreid.engine.ImageSoftmaxEngine(
    datamanager,
    model,
    optimizer=optimizer,
    scheduler=scheduler,
    label_smooth=True
)

weight_path = "/media/User/XXX/deep-person-reid/log/mlfn/mlfn-9cb5a267.pth.tar"

torchreid.utils.load_pretrained_weights(model, weight_path)

engine.run(
    save_dir='log/wobot',
    max_epoch=40,
    eval_freq=10,
    print_freq=10,
    test_only=True,
    visrank = True
)

```
I get the following ERROR when i run my NewDatset.py
```
Traceback (most recent call last):
  File "NewDataset.py", line 121, in <module>
    visrank = True
  File "/media/User/XXX/deep-person-reid/torchreid/engine/engine.py", line 92, in run
    rerank=rerank
  File "/media/User/XXX/deep-person-reid/torchreid/engine/engine.py", line 206, in test
    rerank=rerank
  File "/media/User/.conda/envs/torchreid/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/media/User/XXX/deep-person-reid/torchreid/engine/engine.py", line 281, in _evaluate
    use_metric_cuhk03=use_metric_cuhk03
  File "/media/User/XXX/deep-person-reid/torchreid/metrics/rank.py", line 185, in evaluate_rank
    return evaluate_py(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03)
  File "/media/User/XXX/deep-person-reid/torchreid/metrics/rank.py", line 158, in evaluate_py
    return eval_market1501(distmat, q_pids, g_pids, q_camids, g_camids, max_rank)
  File "/media/User/XXX/deep-person-reid/torchreid/metrics/rank.py", line 145, in eval_market1501
    assert num_valid_q > 0, 'Error: all query identities do not appear in gallery'
AssertionError: Error: all query identities do not appear in gallery
```

**Comment by gmt710** [comment] 2020-07-13 09:04
At least two queries are required.

**Comment by aarti95** [comment] 2020-07-30 11:56
# use your own dataset only
datamanager = torchreid.data.ImageDataManager(
    root='reid-data',
    sources='new_dataset1'
)
​
Building train transforms ...
+ resize to 256x128
+ random flip
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
Building test transforms ...
+ resize to 256x128
+ to torch tensor of range [0, 1]
+ normalization (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
=> Loading train (source) dataset
[['001_c1_0001.jpg', '001_c1_0003.jpg', '001_c1_0023.jpg', '001_c1_0026.jpg', '001_c1_0028.jpg', '001_c1_0031.jpg', '001_c1_0032.jpg', '002_c1_0001.jpg', '002_c1_0008.jpg', '002_c1_0010.jpg', '002_c1_0011.jpg', '002_c1_0012.jpg', '004_c1_0002.jpg', '004_c1_0003.jpg', '004_c1_0016.jpg', '004_c1_0019.jpg', '004_c1_0026.jpg', '004_c1_0029.jpg', '004_c1_0031.jpg', '004_c1_0032.jpg', '004_c1_0038.jpg', '004_c1_0040.jpg', '005_c1_0003.jpg', '005_c1_0004.jpg', '005_c1_0005.jpg', '005_c1_0010.jpg', '005_c1_0016.jpg', '005_c1_0018.jpg', '005_c1_0023.jpg', '005_c1_0027.jpg'], [1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-79-6480387e932a> in <module>
      2 datamanager = torchreid.data.ImageDataManager(
      3     root='reid-data',
----> 4     sources='new_dataset1'
      5 )

D:\deep-person-reid\torchreid\data\datamanager.py in __init__(self, root, sources, targets, height, width, transforms, k_tfm, norm_mean, norm_std, use_gpu, split_id, combineall, load_train_targets, batch_size_train, batch_size_test, workers, num_instances, train_sampler, train_sampler_t, cuhk03_labeled, cuhk03_classic_split, market1501_500k)
    197                 cuhk03_labeled=cuhk03_labeled,
    198                 cuhk03_classic_split=cuhk03_classic_split,
--> 199                 market1501_500k=market1501_500k
    200             )
    201             trainset.append(trainset_)

D:\deep-person-reid\torchreid\data\datasets\__init__.py in init_image_dataset(name, **kwargs)
     38             'but expected to be one of {}'.format(name, avai_datasets)
     39         )
---> 40     return __image_datasets[name](**kwargs)
     41 
     42 

<ipython-input-68-fdee2795a03e> in __init__(self, root, **kwargs)
     96         gallery = galleryListf
     97 
---> 98         super(NewDataset, self).__init__(train, query, gallery, **kwargs)

D:\deep-person-reid\torchreid\data\datasets\dataset.py in __init__(self, train, query, gallery, **kwargs)
    278 
    279     def __init__(self, train, query, gallery, **kwargs):
--> 280         super(ImageDataset, self).__init__(train, query, gallery, **kwargs)
    281 
    282     def __getitem__(self, index):

D:\deep-person-reid\torchreid\data\datasets\dataset.py in __init__(self, train, query, gallery, transform, k_tfm, mode, combineall, verbose, **kwargs)
     53         self.verbose = verbose
     54 
---> 55         self.num_train_pids = self.get_num_pids(self.train)
     56         self.num_train_cams = self.get_num_cams(self.train)
     57 

D:\deep-person-reid\torchreid\data\datasets\dataset.py in get_num_pids(self, data)
    142     def get_num_pids(self, data):
    143         """Returns the number of training person identities."""
--> 144         return self.parse_data(data)[0]
    145 
    146     def get_num_cams(self, data):

D:\deep-person-reid\torchreid\data\datasets\dataset.py in parse_data(self, data)
    135         pids = set()
    136         cams = set()
--> 137         for _, pid, camid in data:
    138             pids.add(pid)
    139             cams.add(camid)

ValueError: too many values to unpack (expected 3)

**Comment by aarti95** [comment] 2020-07-30 11:57
I got the above error if i try to train on my dataset..
