### ISSUE TITLE
The url of DukeMTMC-VideoReID is broken

### ISSUE THREAD

**Issue by BraveApple** [KaiyangZhou/deep-person-reid#181] opened 2019-05-24 03:22 UTC
I can not download DukeMTMC-VideoReID dataset from http://vision.cs.duke.edu/DukeMTMC/data/misc/DukeMTMC-VideoReID.zip.  Can anyone share the pre-downloaded DukeMTMC-VideoReID dataset? Thx.

**Comment by ardiya** [comment] 2019-05-24 05:32
Duplicate of #180

**Comment by KaiyangZhou** [comment] 2019-05-24 16:25
all duke-related datasets are offline, there is no way to download the dataset

**Comment by gceboh** [comment] 2019-05-27 01:46
https://github.com/layumi/DukeMTMC-reID_evaluation/issues/7

**Comment by barotdhrumil21** [comment] 2019-08-10 10:57
> I can not download DukeMTMC-VideoReID dataset from http://vision.cs.duke.edu/DukeMTMC/data/misc/DukeMTMC-VideoReID.zip. Can anyone share the pre-downloaded DukeMTMC-VideoReID dataset? Thx.

did you find anything!? please share here :'(

**Closed** 2019-10-22 21:37 UTC
